In [2]:
import numpy as np

In [3]:
n_samples = 10

In [4]:
np.arange(n_samples) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
X = np.random.rand(n_samples//3, 2)
X

array([[0.06419887, 0.87435275],
       [0.83671189, 0.78233997],
       [0.38835076, 0.79744614]])

In [13]:
np.full((X.shape[1],), 1)

array([1, 1])

In [14]:
np.full((X.shape[1],), -1)

array([-1, -1])

In [15]:
np.full((X.shape[1],), 0)

array([0, 0])

: 